### PR TITLE
Fix payload ids

### LINKED ISSUE #33: Deeplinking not working
Using the `ClientApp` in ExampleApps to connect is not working correctly with the two wallets I have installed on device (Metamask & Rainbow)

If I force it show the QRCode, screenshot it, and then open Rainbow, the flow works. But the deeplinking just opens Metamask, but nothing happens within Metamask.

### PR DESCRIPTION
**Pull request by brunobar79**
This PR changes the way payloadIDs are generated, to match the behavior of the JS SDK (see https://github.com/WalletConnect/walletconnect-monorepo/blob/f04bf82d62c66a562040aeec45e822eb16b79fd9/packages/helpers/utils/src/index.ts#L212)

The values generated by `UUID().hashValue` and `UUID().uuidString` are too big for JS to handle it (see below), which breaks the interaction between a Swift client and  JS client (for example a native (d)app connecting to @rainbow-me wallet (which uses React Native and JS).

Screen Shot 2020-11-03 at 11 51 12 PM

This fixes #33 

Demo: https://recordit.co/PMdIMST99N

### CODE REVIEW

**Comment by DmitryBespalov** [comment]
@brunobar79 thanks for the contribution!

I've got your idea, however, I'd simplify the code a bit (will propose in the comments)

File: Sources/PublicInterface/Request.swift [hunk 1]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
         self.url = url
     }
+    
+    public static func payloadId() -> Int {
+        let now = Int(NSDate().timeIntervalSince1970) * 1000
+        let datePart: Int = now * Int(pow(Double(10),Double(3)))
+        let extraPart: Int = Int(floor(Double.random(in: 0...1) * Double(pow(Double(10),Double(3)))))
+        let payloadId: Int = datePart + extraPart
+        return payloadId
+    }
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:40]:
```suggestion
    /// Generates new ID for a request that is compatible with JS clients.
    /// - Returns: new ID
    public static func payloadId() -> RequestID {
        // Port of the payloadId() from the JS library to make sure that
        // generated IDs fit into JS's number size (max integer size is
        // 2^53 - 1).
        //
        // NOTE: new Date().getTime() is time in milliseconds in JS, however,
        // in iOS it is time in seconds. So instead of 1000, we multiply by 1 million
        //
        // NOTE: the id may still be greater than JS max number, but
        // this would happen if the date is in year 2255
        //
        // JS code:
        //    const datePart: number = new Date().getTime() * Math.pow(10, 3)
        //    const extraPart: number = Math.floor(Math.random() * Math.pow(10, 3))
        //    const id: number = datePart + extraPart
        let datePart = Int(Date().timeIntervalSince1970 * 1000_000)
        let extraPart = Int.random(in: 0..<1000)
        let id = datePart + extraPart
        return id
    }
```

File: Sources/PublicInterface/Request.swift [hunk 2]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
 
-    public convenience init(url: WCURL, method: Method, id: RequestID? = UUID().uuidString) {
-        let payload = JSONRPC_2_0.Request(method: method, params: nil, id: JSONRPC_2_0.IDType(id))
+    public convenience init(url: WCURL, method: Method, id: RequestID? = nil) {
+        let payload = JSONRPC_2_0.Request(method: method, params: nil, id: JSONRPC_2_0.IDType(id != nil ?  id: Self.payloadId()))
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:43]:
```suggestion
    public convenience init(url: WCURL, method: Method, id: RequestID? = payloadId()) {
        let payload = JSONRPC_2_0.Request(method: method, params: nil, id: JSONRPC_2_0.IDType(id))
```

File: Sources/PublicInterface/Request.swift [hunk 3]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
         self.init(payload: payload, url: url)
     }
 
-    public convenience init<T: Encodable>(url: WCURL, method: Method, params: [T], id: RequestID? = UUID().uuidString) throws {
+    public convenience init<T: Encodable>(url: WCURL, method: Method, params: [T], id: RequestID? = nil)  throws {
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:47]:
```suggestion
    public convenience init<T: Encodable>(url: WCURL, method: Method, params: [T], id: RequestID? = payloadId()) throws {
```

File: Sources/PublicInterface/Request.swift [hunk 4]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
         let data = try JSONEncoder.encoder().encode(params)
         let values = try JSONDecoder().decode([JSONRPC_2_0.ValueType].self, from: data)
         let parameters = JSONRPC_2_0.Request.Params.positional(values)
-        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id))
+        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id != nil ?  id: Self.payloadId()))
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:51]:
```suggestion
        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id))
```

File: Sources/PublicInterface/Request.swift [hunk 5]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
         self.init(payload: payload, url: url)
     }
 
-    public convenience init<T: Encodable>(url: WCURL, method: Method, namedParams params: T, id: RequestID? = UUID().uuidString) throws {
+    public convenience init<T: Encodable>(url: WCURL, method: Method, namedParams params: T, id: RequestID? = nil) throws {
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:55]:
```suggestion
    public convenience init<T: Encodable>(url: WCURL, method: Method, namedParams params: T, id: RequestID? = payloadId()) throws {
```

File: Sources/PublicInterface/Request.swift [hunk 6]
```diff
@@ -30,25 +30,33 @@ public class Request {
...
         let data = try JSONEncoder.encoder().encode(params)
         let values = try JSONDecoder().decode([String: JSONRPC_2_0.ValueType].self, from: data)
         let parameters = JSONRPC_2_0.Request.Params.named(values)
-        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id))
+        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id != nil ?  id: Self.payloadId()))
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Request.swift:59]:
```suggestion
        let payload = JSONRPC_2_0.Request(method: method, params: parameters, id: JSONRPC_2_0.IDType(id))
```

File: Sources/PublicInterface/Client.swift [hunk 7]
```diff
@@ -184,7 +184,7 @@ public class Client: WalletConnect {
             delegate.client(self, didConnect: existingSession)
         } else { // establishing new connection, handshake in process
             communicator.subscribe(on: dAppInfo.peerId, url: url)
-            let request = try! Request(url: url, method: "wc_sessionRequest", params: [dAppInfo], id: UUID().hashValue)
+            let request = try! Request(url: url, method: "wc_sessionRequest", params: [dAppInfo], id: nil)
```
Comment (DmitryBespalov) [inline Sources/PublicInterface/Client.swift:187]:
```suggestion
            let request = try! Request(url: url, method: "wc_sessionRequest", params: [dAppInfo], id: Request.payloadId())
```

**Review by DmitryBespalov — CHANGES_REQUESTED** [review]
Here, suggested changes

**Comment by brunobar79** [comment]
Totally agree with the suggestions!  Should be good now. Thanks @DmitryBespalov

**Review by DmitryBespalov — APPROVED** [review]

**Comment by simibac** [comment]
> Demo: https://recordit.co/PMdIMST99N

@brunobar79 Could you please share your code, how you connected with the Rainbow wallet? The method for connecting to the wallet is not working for me...
